# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cache-Static
version:      0.9905
version_from: lib/Cache/Static.pm
installdirs:  site
license:      gpl
requires:
    Digest::MD5:                   0
    Storable:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
